export const FallingInLoveList = [
  "eu te amo",
  "te amo",
  "amo você",
  "amo voce",
  "eu amo você",
  "te ama",
  "te adora",
  "gosta de tu",
  "adora tu",
  "gosta de vc",
  "gosta de voce",
  "gosta de você",
  "eu amo voce",
  "eu te adoro",
  "te adoro",
  "adoro você",
  "adoro voce",
  "eu adoro você",
]

export const MarryList = [
  "casa comigo",
  "casar comigo",
  "quer casar comigo",
  "quer casar comigo?",
  "casa comigo?",
  "casar comigo?",
  "case comigo",
  "merry me",
  "marry me",
  "quer casar comigo",
]